# Generated by Django 5.2.7 on 2025-11-14 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField(unique=True)),
                ('kapasitas', models.IntegerField()),
                ('harga_per_orang', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategori', models.CharField(choices=[('makanan', 'Makanan'), ('minuman', 'Minuman')], max_length=50)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemesan', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tanggal_reservasi', models.DateField()),
                ('jam_reservasi', models.TimeField()),
                ('jumlah_orang', models.IntegerField()),
                ('harga_tempat_per_orang', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_menu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_harga', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dp_nominal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sudah_bayar_dp', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Menunggu DP'), ('confirmed', 'Sudah DP'), ('cancelled', 'Dibatalkan'), ('completed', 'Selesai')], default='pending', max_length=20)),
                ('waktu_dibuat', models.DateTimeField(auto_now_add=True)),
                ('meja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservasi.meja')),
            ],
        ),
    ]
