# Generated by Django 5.2.7 on 2025-11-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_dp/'),
        ),
    ]
