# Generated by Django 5.2.7 on 2025-11-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0005_remove_order_menu_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meja',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='meja_images/'),
        ),
    ]
