# Generated by Django 5.2.7 on 2025-12-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0009_remove_order_customer_name_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Bayar di Kasir'), ('qris', 'QRIS'), ('transfer', 'Transfer Bank')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
