# Generated by Django 5.2.7 on 2025-12-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0010_order_payment_method_order_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qris_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
