# Generated by Django 5.2.7 on 2025-12-05 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0011_order_billing_code_order_qris_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qris_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='table_number',
        ),
    ]
