# Generated by Django 5.2.7 on 2025-12-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0013_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
