# Generated by Django 5.2.7 on 2025-12-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0014_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('process', 'Sedang Diproses'), ('done', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
