# Generated by Django 5.2.7 on 2025-12-18 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0016_order_booking_order_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservasi.booking'),
        ),
    ]
